# Generated by Django 5.1 on 2024-08-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='thumbnail',
            field=models.FileField(default=False, upload_to='thumbnail/'),
        ),
    ]
