# Generated by Django 5.1 on 2024-08-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subtitle_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='is_active',
        ),
    ]
