# Generated by Django 5.1 on 2024-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subtitle_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
